#!/usr/bin/env node
/**
 * Downloads the site's photography from Unsplash into `public/assets/photo/`.
 *
 * ## Why the files are committed rather than hotlinked
 *
 * Pointing `<img>` at `images.unsplash.com` would put a third-party origin on
 * every page load — a runtime dependency on someone else's CDN, a request the
 * visitor did not ask for, and an exception the Content-Security-Policy in
 * `SECURITY.md` §3 would have to carry forever. Downloading once means the site
 * serves its own bytes and the CSP stays closed.
 *
 * ## Licensing
 *
 * These are Unsplash photographs, downloaded on the owner's explicit
 * instruction (2026-09-02), and the owner is handling the licence review.
 * Attribution for every file is generated into `docs/photo-credits.md` — do not
 * delete it, and do not add a photograph here without adding its photographer.
 *
 * ## Running it
 *
 *   npm run gen:photos
 *
 * The output is committed, so this is not part of the build. It exists so the
 * provenance of each file is recorded in code rather than in someone's memory,
 * and so the set can be re-fetched or extended.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";
import { tmpdir } from "node:os";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = resolve(ROOT, "public/assets/photo");

/** Long edge, in px. Big enough for a full-bleed cell on a 2x display. */
const WIDTH = 1600;
/** JPEG quality. The images are backdrops, not the subject. */
const QUALITY = 62;

/*
 * A note on what is *not* in the set: a concrete-wall texture was tried and cut.
 * Fine high-entropy grain is the one thing JPEG cannot compress — it came in at
 * 1.1 MB for a flat grey surface the paper token already provides. If a photo
 * here ever lands above ~350 KB, it is the wrong photo, not the wrong quality.
 */

/**
 * The set.
 *
 * Chosen to sit with the drawing rather than fight it: tangled line, long
 * exposure, and bare surface. Nothing literal — no offices, no laptops, no
 * people at whiteboards. `id` is the filename the site references.
 */
const PHOTOS = [
  {
    id: "wire-dark",
    url: "https://images.unsplash.com/photo-1687038520579-8d8f24721267",
    alt: "A pile of black wires resting on each other",
    credit: "Kier in Sight Archives",
    handle: "kierinsightarchives",
    page: "https://unsplash.com/photos/a-pile-of-black-wires-sitting-on-top-of-each-other-WdnrKQzwEAI",
  },
  {
    id: "wire-tangle",
    url: "https://images.unsplash.com/photo-1764866113233-ab57bdc25360",
    alt: "A tangled mass of fine coloured wire",
    credit: "Kier in Sight Archives",
    handle: "kierinsightarchives",
    page: "https://unsplash.com/photos/a-tangled-mess-of-colorful-thin-wires-hieyx6am3CA",
  },
  {
    id: "fibre",
    url: "https://images.unsplash.com/photo-1742774101928-f7e92a471c1b",
    alt: "Blue fibre-optic strands radiating outward",
    credit: "S. Raze",
    handle: "sraze",
    page: "https://unsplash.com/photos/blue-fiber-optic-cables-are-radiating-outwards-WN0alo23Yhg",
  },
  {
    id: "trails",
    url: "https://images.unsplash.com/photo-1550275994-2bc88dc68637",
    alt: "Long-exposure light trails in blue",
    credit: "Bru-nO",
    handle: "bruthethe",
    page: "https://unsplash.com/photos/abstract-long-exposure-light-trails-qyhLjwn6Gpc",
  },
];

const work = resolve(tmpdir(), `gal-photos-${process.pid}`);
await mkdir(work, { recursive: true });
await mkdir(OUT_DIR, { recursive: true });

for (const photo of PHOTOS) {
  // `w` and `q` are Unsplash's own delivery parameters, so the CDN does the
  // resize and we never pull a 20 MB original across the wire.
  const source = `${photo.url}?auto=format&fit=crop&w=${WIDTH}&q=80`;
  const raw = resolve(work, `${photo.id}.jpg`);
  const out = resolve(OUT_DIR, `${photo.id}.jpg`);

  execFileSync("curl", ["-sL", "--fail", "--max-time", "60", source, "-o", raw]);
  // Re-encode locally so every file has the same quality regardless of what the
  // CDN decided to send.
  execFileSync("sips", [
    "-s",
    "format",
    "jpeg",
    "-s",
    "formatOptions",
    String(QUALITY),
    "--resampleWidth",
    String(WIDTH),
    raw,
    "--out",
    out,
  ]);

  const { size } = await import("node:fs").then((fs) => fs.promises.stat(out));
  console.log(`${photo.id}.jpg — ${(size / 1024).toFixed(0)} KB`);
}

const credits = `# Photo credits

Generated by \`npm run gen:photos\` (scripts/fetch-photos.mjs). Do not edit by
hand — add the photograph to that script instead.

Every image in \`public/assets/photo/\` is an Unsplash photograph, downloaded and
served from our own origin rather than hotlinked (see the script for why). They
were added on the owner's instruction; **licence review is the owner's**, and it
is tracked with the other launch items in \`SECURITY.md\` §10.

| File | Photographer | Source |
| ---- | ------------ | ------ |
${PHOTOS.map((p) => `| \`${p.id}.jpg\` | [${p.credit}](https://unsplash.com/@${p.handle}) | [Unsplash](${p.page}) |`).join("\n")}
`;

await writeFile(resolve(ROOT, "docs/photo-credits.md"), credits, "utf8");
console.log("docs/photo-credits.md written");
